# Exported from Render on 2026-01-18T12:44:38Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: unit-site
      runtime: node
      repo: https://github.com/tommylive1403/unit-site
      plan: free
      region: virginia
      buildCommand: yarn
      startCommand: go
<<<<<<< HEAD
      autoDeployTrigger: "on"
=======
      autoDeployTrigger: "off"
>>>>>>> bb247a3d54b1daf08f500efa8bfa0c48e4e5b126
